/* Agent readiness — renders data/capability_data.json.
 *
 * The file is generated by `changelogs/ui/generate_data.py` in the virgil repo. Nothing
 * here computes a verdict, derives a date, or decides what a cell means: if a number is
 * not in the JSON it does not belong on the page. That split is deliberate — the
 * analysis has to be reproducible from its own repo, and a page that quietly recomputes
 * something is a second source of truth waiting to disagree with the first.
 */

const VENDOR_COLOR = {
    hex:      '#FF6B35',
    metabase: '#2E86AB',
    omni:     '#7B2CBF',
    sigma:    '#00A86B',
};

const STATE_WORD = { yes: 'has it', partial: 'partial', no: "doesn't" };

let DATA = null;

/* ------------------------------------------------------------------ utils */

const el = (tag, cls, text) => {
    const n = document.createElement(tag);
    if (cls) n.className = cls;
    if (text != null) n.textContent = text;
    return n;
};

const vendorLabel = (slug) =>
    (DATA.meta.vendors.find(v => v.slug === slug) || {}).label || slug;

/** "2026-06-16" -> "Jun 2026". Month precision only: these are announcement dates,
 *  and a day-precise label invites comparisons the data cannot support. */
function monthLabel(iso) {
    if (!iso) return '';
    const [y, m] = iso.split('-');
    const names = ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'];
    return `${names[parseInt(m, 10) - 1]} ${y}`;
}

const toNum = (iso) => {
    const [y, m, d] = iso.split('-').map(Number);
    return y + (m - 1) / 12 + (d - 1) / 365;
};

/* ------------------------------------------------------------- provenance */

function renderProvenance() {
    const m = DATA.meta;
    const wrap = document.getElementById('ar-provenance');
    const items = [
        [m.docs_corpus.pages.toLocaleString(), 'pages of documentation read'],
        [m.changelog.items.toLocaleString(), 'changelog items coded'],
        [m.counts.doc_sourced + '/' + m.counts.cells, 'cells sourced to a doc page'],
        [DATA.sources.length, 'pages archived'],
    ];
    items.forEach(([n, label]) => {
        const d = el('div', 'ar-prov-item');
        d.appendChild(el('span', 'ar-prov-num', n));
        d.appendChild(el('span', 'ar-prov-label', label));
        wrap.appendChild(d);
    });

    const gatesPass = m.gates.every(g => g.pass);
    const g = el('div', 'ar-prov-item');
    g.appendChild(el('span', 'ar-prov-num' + (gatesPass ? ' ar-prov-gate' : ''),
                     gatesPass ? '✓' : '✗'));
    g.appendChild(el('span', 'ar-prov-label',
                     gatesPass ? 'evidence gates pass' : 'evidence gates FAIL'));
    wrap.appendChild(g);

    document.getElementById('ar-caveat').textContent =
        `Read ${m.generated}. Present-day capability comes from each vendor's live ` +
        `documentation; arrival dates come from their changelogs and mean "first ` +
        `announced", which is not the same as "first shipped". Comparison window opens ` +
        `${monthLabel(m.changelog.window_opens)}, when the shortest archive here begins — ` +
        `before that, a vendor being unmarked means nobody could have seen it, not that ` +
        `it was missing.`;
}

/* ----------------------------------------------------------------- matrix */

function chipFor(rowId, vendor) {
    const cell = DATA.cells[`${rowId}|${vendor}`] || {};
    const docs = cell.docs;
    const state = docs ? docs.state : 'no';
    const flagged = cell.quadrant === 'shipped-quietly' ||
                    cell.quadrant === 'marketed-not-found';

    const btn = el('button', `ar-chip is-${state}${flagged ? ' is-flagged' : ''}`);
    btn.type = 'button';
    btn.setAttribute('aria-label',
        `${vendorLabel(vendor)}: ${STATE_WORD[state] || state}. Open the evidence.`);
    btn.appendChild(el('span', 'ar-chip-state', STATE_WORD[state] || state));

    if (docs && docs.scope) btn.appendChild(el('span', 'ar-chip-scope', docs.scope));

    const cl = cell.changelog;
    const date = el('span', 'ar-chip-date' + (cl && cl.prewindow ? ' is-pre' : ''),
                    cl ? (cl.prewindow ? '‹ ' : '') + monthLabel(cl.date) : '—');
    btn.appendChild(date);

    btn.addEventListener('click', () => openDrawer(rowId, vendor));
    return btn;
}

function renderMatrix() {
    const table = document.getElementById('ar-matrix');
    const vendors = DATA.meta.vendors;

    const thead = el('thead');
    const htr = el('tr');
    htr.appendChild(el('th', 'ar-th-row', 'Capability'));
    vendors.forEach(v => htr.appendChild(el('th', 'ar-th-vendor', v.label)));
    thead.appendChild(htr);
    table.appendChild(thead);

    const tbody = el('tbody');
    DATA.groups.forEach(group => {
        const gtr = el('tr', 'ar-group-row');
        const gtd = el('td');
        gtd.colSpan = vendors.length + 1;
        gtd.appendChild(el('span', 'ar-group-name', group.name));
        gtd.appendChild(el('span', 'ar-group-sub', group.sub));
        gtr.appendChild(gtd);
        tbody.appendChild(gtr);

        group.rows.forEach(row => {
            const tr = el('tr');
            const label = el('td', 'ar-row-label');
            label.appendChild(el('div', 'ar-row-title', row.label));
            label.appendChild(el('div', 'ar-row-sub', row.sub));
            tr.appendChild(label);
            vendors.forEach(v => {
                const td = el('td', 'ar-cell');
                td.appendChild(chipFor(row.id, v.slug));
                tr.appendChild(td);
            });
            tbody.appendChild(tr);
        });
    });
    table.appendChild(tbody);

    const toggle = document.getElementById('toggle-dates');
    toggle.addEventListener('change', () => {
        document.querySelectorAll('.ar-chip')
            .forEach(c => c.classList.toggle('hide-dates', !toggle.checked));
    });
}

/* --------------------------------------------------------------- timeline */

function renderTimeline() {
    const wrap = document.getElementById('ar-timeline');
    const dated = Object.values(DATA.cells).filter(c => c.changelog);
    if (!dated.length) return;

    const lo = Math.floor(Math.min(...dated.map(c => toNum(c.changelog.date))));
    const hi = Math.ceil(Math.max(...dated.map(c => toNum(c.changelog.date))));
    // Inset both ends: a dot is 15px wide and a year label is wider still, so a point
    // at exactly 0% or 100% gets half-clipped by the track's own edge.
    const PAD = 4;
    const pct = (n) => PAD + ((n - lo) / (hi - lo)) * (100 - 2 * PAD);

    const axis = el('div', 'ar-tl-axis');
    for (let y = lo; y <= hi; y++) {
        const g = el('div', 'ar-tl-gridline');
        g.style.left = pct(y) + '%';
        axis.appendChild(g);
        const t = el('div', 'ar-tl-tick', String(y));
        t.style.left = pct(y) + '%';
        axis.appendChild(t);
    }
    wrap.appendChild(axis);

    DATA.groups.forEach(group => {
        wrap.appendChild(el('div', 'ar-tl-group', group.name));

        // Ordered by first arrival so the reader's eye tracks the race, except for the
        // outside-agent group: those rows are a depth ladder (answer, then meanings,
        // then lineage, then write) and date order puts write above read, which reads
        // as nonsense even when every date is right.
        const rows = group.name === 'OUTSIDE AGENTS' ? group.rows.slice() :
            group.rows.slice().sort((a, b) => {
                const first = (r) => Math.min(...DATA.meta.vendors.map(v => {
                    const c = DATA.cells[`${r.id}|${v.slug}`];
                    return c && c.changelog ? toNum(c.changelog.date) : Infinity;
                }));
                return first(a) - first(b);
            });

        rows.forEach(row => {
            const tr = el('div', 'ar-tl-row');
            const lab = el('div', 'ar-tl-label');
            lab.appendChild(el('div', 't', row.label));
            lab.appendChild(el('div', 's', row.sub));
            tr.appendChild(lab);

            const track = el('div', 'ar-tl-track');
            const points = DATA.meta.vendors
                .map(v => ({ v: v.slug, c: DATA.cells[`${row.id}|${v.slug}`] }))
                .filter(p => p.c && p.c.changelog)
                .map(p => ({ ...p, n: toNum(p.c.changelog.date) }))
                .sort((a, b) => a.n - b.n);

            if (!points.length) {
                track.appendChild(el('div', 'ar-tl-empty', 'nobody has announced this'));
            } else if (points.length > 1) {
                const span = el('div', 'ar-tl-span');
                span.style.left = pct(points[0].n) + '%';
                span.style.width = (pct(points[points.length - 1].n) - pct(points[0].n)) + '%';
                track.appendChild(span);
            }

            // Three vendors shipping MCP within a fortnight is a real and interesting
            // fact, but drawn flat it is one smudge. Overlapping dots step vertically
            // so the cluster stays readable without moving anything along the axis.
            let lastX = -99, tier = 0;
            points.forEach(p => {
                const x = pct(p.n);
                tier = (x - lastX) < 1.6 ? tier + 1 : 0;
                lastX = x;
                const dot = el('div', 'ar-tl-dot' + (p.c.changelog.prewindow ? ' is-pre' : ''));
                dot.style.marginTop = (-7.5 + (tier % 2 ? 8 : 0) * (tier % 4 < 2 ? 1 : -1)) + 'px';
                dot.style.left = x + '%';
                dot.style.background = VENDOR_COLOR[p.v];
                dot.style.borderColor = p.c.changelog.prewindow ? VENDOR_COLOR[p.v] : '#fff';
                dot.title = `${vendorLabel(p.v)} — ${monthLabel(p.c.changelog.date)}` +
                            (p.c.changelog.prewindow ? ' (before the window opened)' : '');
                dot.addEventListener('click', () => openDrawer(row.id, p.v));
                track.appendChild(dot);
            });

            tr.appendChild(track);
            wrap.appendChild(tr);
        });
    });

    const key = el('div', 'ar-tl-vendors');
    DATA.meta.vendors.forEach(v => {
        const k = el('span', 'ar-tl-vkey');
        const i = el('i');
        i.style.background = VENDOR_COLOR[v.slug];
        k.appendChild(i);
        k.appendChild(document.createTextNode(v.label));
        key.appendChild(k);
    });
    wrap.appendChild(key);
}

/* ---------------------------------------------------------- disagreements */

const KIND_TITLE = {
    'shipped-quietly': 'Shipped quietly',
    'marketed-not-found': 'Marketed, not found',
};

function renderDisagreements() {
    const wrap = document.getElementById('ar-disagree');
    if (!DATA.disagreements.length) {
        wrap.appendChild(el('p', 'ar-lede-secondary',
            'On this reading the two sources agree everywhere.'));
        return;
    }
    DATA.disagreements.forEach(d => {
        const card = el('button', 'ar-dcard');
        card.type = 'button';
        card.appendChild(el('div', 'ar-dcard-kind', KIND_TITLE[d.kind] || d.kind));
        const h = el('h3');
        h.appendChild(el('span', 'ar-dcard-vendor', vendorLabel(d.vendor)));
        h.appendChild(document.createTextNode(' — ' + d.label));
        card.appendChild(h);
        card.appendChild(el('p', null, d.detail));
        card.addEventListener('click', () => openDrawer(d.row, d.vendor));
        wrap.appendChild(card);
    });
}

/* ----------------------------------------------------------------- sources */

function renderSources() {
    const list = document.getElementById('ar-sources');
    const wayback = DATA.sources.filter(s => s.tier === 'wayback').length;
    const local = DATA.sources.filter(s => s.tier === 'local').length;
    document.getElementById('ar-source-count').textContent =
        `${wayback} on the Wayback Machine, ${local} held as a local capture because ` +
        `Wayback would not index them — those are weaker, and marked.`;

    DATA.sources.forEach(s => {
        const li = el('li');
        li.dataset.search = s.url.toLowerCase();

        const tier = el('span', 'ar-tier ar-tier-' + (s.tier || 'local'), s.tier || '—');
        li.appendChild(tier);

        const a = el('a', 'ar-src-url', s.url);
        a.href = s.url;
        a.target = '_blank';
        a.rel = 'noopener';
        li.appendChild(a);

        if (s.archived) {
            const arch = el('a', 'ar-d-link', 'archived copy');
            arch.href = s.archived;
            arch.target = '_blank';
            arch.rel = 'noopener';
            li.appendChild(arch);
        }
        if (s.note) li.appendChild(el('div', 'ar-src-note', s.note));
        list.appendChild(li);
    });

    const filter = document.getElementById('ar-source-filter');
    filter.addEventListener('input', () => {
        const q = filter.value.trim().toLowerCase();
        list.querySelectorAll('li').forEach(li => {
            li.hidden = q && !li.dataset.search.includes(q);
        });
    });
}

/* ------------------------------------------------------------------ drawer */

function block(labelText, subText, node) {
    const b = el('div', 'ar-d-block');
    b.appendChild(el('div', 'ar-d-label', labelText));
    if (subText) b.appendChild(el('div', 'ar-d-label-sub', subText));
    b.appendChild(node);
    return b;
}

function findRow(rowId) {
    for (const g of DATA.groups) {
        const r = g.rows.find(x => x.id === rowId);
        if (r) return { row: r, group: g };
    }
    return {};
}

function openDrawer(rowId, vendor) {
    const cell = DATA.cells[`${rowId}|${vendor}`];
    if (!cell) return;
    const { row, group } = findRow(rowId);
    const docs = cell.docs;
    const L = DATA.labels;
    const body = document.getElementById('ar-drawer-body');
    body.innerHTML = '';

    body.appendChild(el('div', 'ar-d-eyebrow', group.name));
    body.appendChild(el('div', 'ar-d-title', `${vendorLabel(vendor)} — ${row.label}`));
    body.appendChild(el('div', 'ar-d-sub', row.sub));

    const state = docs ? docs.state : 'no';
    const verdict = el('div', `ar-d-verdict is-${state}`);
    verdict.appendChild(el('span', null, STATE_WORD[state] || state));
    if (docs && docs.scope) verdict.appendChild(el('span', 'ar-chip-scope', docs.scope));
    body.appendChild(verdict);

    if (docs && docs.quotes && docs.quotes.length) {
        const holder = el('div');
        docs.quotes.forEach(q => holder.appendChild(el('blockquote', 'ar-quote', '“' + q + '”')));
        body.appendChild(block(L.verbatim, L.verbatim_sub, holder));
    }

    if (docs && docs.enumeration && docs.enumeration.length) {
        const ul = el('ul', 'ar-d-enum');
        docs.enumeration.forEach(x => ul.appendChild(el('li', null, x)));
        body.appendChild(block(L.absence,
            'the complete list on the page — the capability is not in it', ul));
    }

    if (docs && docs.normalized) {
        body.appendChild(block(L.normalized, L.normalized_sub,
            el('div', 'ar-normalized', docs.normalized)));
    }

    if (docs && docs.note) {
        body.appendChild(block(L.ours, L.ours_sub, el('div', 'ar-reading', docs.note)));
    }

    if (cell.changelog) {
        const cl = el('div', 'ar-normalized');
        cl.textContent = `First announced ${monthLabel(cell.changelog.date)}` +
            (cell.changelog.headline ? ` — ${cell.changelog.headline}` : '') +
            (cell.changelog.prewindow
                ? '. This predates the comparison window, so it is real for this vendor '
                  + 'but is not a head start over the others.'
                : '.');
        body.appendChild(block('IN THE CHANGELOG',
            'when the vendor first said it — not necessarily when it shipped', cl));
    } else {
        const cl = el('div', 'ar-normalized');
        cl.textContent = docs && docs.state !== 'no'
            ? 'Nothing in the changelog announces this. It is in the docs today, so it '
              + 'shipped without being marketed.'
            : 'Nothing in the changelog announces this.';
        body.appendChild(block('IN THE CHANGELOG', null, cl));
    }

    const links = el('div', 'ar-d-links');
    if (docs && docs.url) {
        const a = el('a', 'ar-d-link', 'the page it came from →');
        a.href = docs.url; a.target = '_blank'; a.rel = 'noopener';
        links.appendChild(a);
    }
    if (docs && docs.archived && docs.archived.url) {
        const a = el('a', 'ar-d-link', 'archived copy →');
        a.href = docs.archived.url; a.target = '_blank'; a.rel = 'noopener';
        links.appendChild(a);
    }
    (docs && docs.sources ? docs.sources : []).slice(1).forEach(s => {
        const a = el('a', 'ar-d-link', s.title.slice(0, 42) + ' →');
        a.href = s.url; a.target = '_blank'; a.rel = 'noopener';
        links.appendChild(a);
    });
    if (links.children.length) body.appendChild(block('SOURCES', null, links));

    if (docs) {
        const meta = el('div', 'ar-d-meta');
        const bits = [];
        if (docs.checked) bits.push(`Read ${docs.checked}.`);
        if (docs.archived && docs.archived.tier === 'local') {
            bits.push('Archived only as a local capture — Wayback would not index this ' +
                      'page, so the snapshot is self-hosted and therefore weaker evidence ' +
                      'than a third-party archive.');
        }
        if (docs.confidence) bits.push(`Confidence: ${docs.confidence}.`);
        meta.textContent = bits.join(' ');
        if (bits.length) body.appendChild(meta);
    }

    document.getElementById('ar-drawer').hidden = false;
    document.getElementById('ar-scrim').hidden = false;
    document.body.style.overflow = 'hidden';
    if (window.rudderanalytics) {
        rudderanalytics.track('Evidence Opened', { row: rowId, vendor: vendor });
    }
}

function closeDrawer() {
    document.getElementById('ar-drawer').hidden = true;
    document.getElementById('ar-scrim').hidden = true;
    document.body.style.overflow = '';
}

/* -------------------------------------------------------------------- boot */

fetch('data/capability_data.json')
    .then(r => r.json())
    .then(d => {
        DATA = d;
        renderProvenance();
        renderMatrix();
        renderTimeline();
        renderDisagreements();
        renderSources();

        document.getElementById('ar-drawer-close').addEventListener('click', closeDrawer);
        document.getElementById('ar-scrim').addEventListener('click', closeDrawer);
        document.addEventListener('keydown', e => { if (e.key === 'Escape') closeDrawer(); });
    })
    .catch(err => {
        console.error('capability data failed to load', err);
        document.getElementById('ar-provenance').textContent =
            'The data for this page failed to load.';
    });
